name: uname
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  windows-2022:
    runs-on: windows-2022
    steps:
      - run: |
          uname -a
          uname -m
          uname -o
          uname -s
          arch
  windows-2019:
    runs-on: windows-2019
    steps:
      - run: |
          uname -a
          uname -m
          uname -o
          uname -s
          arch
  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          uname -a
          uname -m
          uname -o
          uname -s
          arch
  ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          uname -a
          uname -m
          uname -o
          uname -s
          arch
  macos-12:
    runs-on: macos-12
    steps:
      - run: |
          uname -a
          uname -m
          # uname -o
          uname -s
          arch
  macos-11:
    runs-on: macos-11
    steps:
      - run: |
          uname -a
          uname -m
          # uname -o
          uname -s
          arch
